#!/bin/bash

ROOT_DIR=$(cd `dirname $0` && cd .. && pwd)
HOOKS_DIR="${ROOT_DIR}/git/hooks"

function usage {
    if [ -n "$1" ]; then
        echo "ERROR: $1"
        echo
    fi
    echo Usage:
    echo "  $(basename $0) --help"
    echo "  $(basename $0) <path-to-git-repo> <hook-type ...>"
    echo "  $(basename $0) --list"
    echo
    echo "Installs hooks into the given git repository."
    echo "The --list option lists the available hook types."
    echo
    exit 1
}

REPO=""

function list_categories {
    echo "Hook types:"
    for hook in $(cd  "${HOOKS_DIR}" && ls -1); do
        [ -d "${HOOKS_DIR}/${hook}" ] && echo "  ${hook}"
    done
    exit 0
}

[ -z "$1" ] && usage "must specify a git repository"

case "$1" in
    -h|-help|--help)
        usage
        ;;
    -l|-list|--list)
        list_categories
        ;;
    *)
        REPO="$1"
        ;;
esac
shift

[ -z "$1" ] && usage " must specify at least one hook category or all to install all"

GIT_DIR="${REPO}/.git"
[ -d "${GIT_DIR}" ] || usage "${GIT_DIR} does not exist or is not a directory"

GITHOOKS_DIR="$GIT_DIR/hooks"
[ -d "${GITHOOKS_DIR}" ] || usage "${GITHOOKS_DIR} does not exist or is not a directory"

function check_hook {
    local TYPE="$1"
    HOOK_SRC="${HOOKS_DIR}/${TYPE}"
    [ -d "${HOOK_SRC}" ] || usage "invalid hook type ${TYPE}"
}

function install_hook {
    local TYPE="$1"
    HOOK_SRC="${HOOKS_DIR}/${TYPE}"

    for name in $(cd "${HOOK_SRC}" && ls -1); do
        HOOK="${HOOK_SRC}/${name}"
        [ -x "${HOOK}" ] || "${HOOK} is not executable"

        echo "Installing ${name} from ${HOOK}"
        (cd "${GITHOOKS_DIR}" && ln -sf "${HOOK}")
    done
}

if [[ "$1" == "all" ]]; then
    for name in $(cd  "${HOOKS_DIR}" && ls -1); do
        if [ -d "${HOOKS_DIR}/${name}" ]; then
            check_hook "${name}"
        fi
    done

    for name in $(cd  "${HOOKS_DIR}" && ls -1); do
        if [ -d "${HOOKS_DIR}/${name}" ]; then
            install_hook "${name}"
        fi
    done
    exit 0
fi

for name in $(echo "$@"); do
    if [[ "${name}" == "all" ]]; then
        usage "can only use all as the first hook type"
    fi

    check_hook "${name}"
done

while [ -n "$1" ]; do
    install_hook "$1"
    shift
done
