#!/bin/bash

DEFAULT_KUBECTL="kubectl"
DEFAULT_KUBECTL_CONFIG="$TBN_WORKSPACE/secrets/kubernetes/clusters/kube-1-prod-us-east-1/kubeconfig"

function err {
    echo "$@" >&2
}

function usage {
    err "Usage: $0 [options] SELECTOR FILE"
    err
    err "  SELECTOR is a kubectl pod selector, quoted to be a single command line"
    err "  argument. FILE is the path to a file in the pod."
    err
    err "Options:"
    err "    -c CONTAINER, --container=CONTAINER"
    err "      Selects a specific container within the pod from which files are"
    err "      retrieved."
    err
    err "    --kubectl=CMD"
    err "      Use CMD to invoke kubectl. Defaults to $DEFAULT_KUBECTL"
    err
    err "    -k CONFIG, --kubeconfig=CONFIG"
    err "      Use CONFIG as the kubeconfig for kubectl. Defaults to"
    err "      $DEFAULT_KUBECTL_CONFIG"
    err
    err "    -o FILE, --output=FILE"
    err "      Redirects all data to the given file, concatenating results from"
    err "      multiple pods. Exising files will not be overwritten. Ignored if"
    err "      --split is specified."
    err
    err "    -s, --split[=DIR]"
    err "      Redirects datas to a file per pod, with the file's base name as a"
    err "      suffix. Existing files will not be overwritten. If DIR is specified,"
    err "      the given directory is used to store the files. The directory is"
    err "      created, if necessary. Overrides --output."
    err
    exit 1
}

function split {
    RESULT=`echo "$1" | cut -d= -f2`
    if [ -z "$RESULT" ]; then
        err "missing value in $1"
        usage
    fi
    echo "$RESULT"
}

SELECTOR=""
FILE=""

KUBECTL="$DEFAULT_KUBECTL"
KUBECTL_CONFIG="$DEFAULT_KUBECTL_CONFIG"
OUTPUT=""
SPLIT=false
SPLIT_DIR="."

CONTAINER=""

while [ -n "$1" ]; do
    ARG="$1"
    shift
    case "$ARG" in
        -c)
            if [ -n "$1" ]; then
                CONTAINER="$1"
            else
                err "missing container for $ARG"
                usage
            fi
            shift
            ;;

        --container=*)
            CONTAINER=`split $ARG`
            ;;

        -h|-help|--help)
            usage
            ;;

        --kubectl=*)
            KUBECTL=`split "$ARG"`
            ;;

        -k)
            if [ -n "$1" ]; then
                KUBECTL_CONFIG="$1"
            else
                err "missing kubeconfig for $ARG"
                usage
            fi
            shift
            ;;

        --kubeconfig=*)
            KUBECTL_CONFIG=`split $ARG`
            ;;

        -o)
            if [ -n "$1" ]; then
                OUTPUT="$1"
            else
                err "missing file for $ARG"
                usage
            fi
            shift
            ;;

        --output=*)
            OUTPUT=`split "$ARG"`
            ;;

        -s|--split)
            SPLIT=true
            ;;

        --split=*)
            SPLIT=true
            SPLIT_DIR=`split "$ARG"`
            ;;

        *)
            if [ -z "$SELECTOR" ]; then
                SELECTOR="$ARG"
            elif [ -z "$FILE" ]; then
                FILE="$ARG"
            else
                err "unexpected argument $ARG"
                usage
            fi
            ;;
    esac
done

if [ -z "$SELECTOR" ]; then
    err "missing selector argument"
    usage
fi

if [ -z "$FILE" ]; then
    err "missing file argument"
    usage
fi

EXEC_ARGS=""
[ -n "$CONTAINER" ]  && EXEC_ARGS="$EXEC_ARGS --container=$CONTAINER"

if $SPLIT; then
    OUTPUT=""
    mkdir -p "$SPLIT_DIR"
fi

if [ -n "$OUTPUT" -a -e "$OUTPUT" ]; then
    err "output '$OUTPUT' exists"
    usage
fi

BASEFILE=`basename "$FILE"`

$KUBECTL --kubeconfig="$KUBECTL_CONFIG" get pods -l "$SELECTOR" -o json \
    | jq -r '.items[].metadata.name' \
    | (while read POD; do
           OK=true
           REDIR=""
           if [ -n "$OUTPUT" ]; then
               REDIR="$OUTPUT"
           elif $SPLIT; then
               SPLIT_FILE="$SPLIT_DIR/${POD}-${BASEFILE}"
               if [ -e "$SPLIT_FILE" ]; then
                   err "skipping $POD, because $SPLIT_FILE already exists"
                   OK=false
               fi
               REDIR="$SPLIT_FILE"
           fi

           if $OK; then
               if [ -n "$REDIR" ]; then
                   $KUBECTL --kubeconfig="$KUBECTL_CONFIG" exec $EXEC_ARGS "$POD" -- bash -c "cat '$FILE' | gzip -c" | gunzip -c >>"$REDIR"
               else
                   $KUBECTL --kubeconfig="$KUBECTL_CONFIG" exec $EXEC_ARGS "$POD" -- bash -c "cat '$FILE' | gzip -c" | gunzip -c
               fi
           fi
       done)
