#!/bin/bash

if ! which pandoc; then
    echo "pandoc not installed: cannot format markdown" >/dev/stderr
    exit 1
fi

DIR=`mktemp -d -t mdless`

declare -a LESS_FILES
let X=0

for FILE in "$@"; do
    BASENAME=`basename $FILE`
    OUT="$DIR/$BASENAME"
    while [ -e "$OUT" ]; do
        OUT="${OUT}X"
    done
    pandoc -s -f markdown -t man "$FILE" | groff -T utf8 -man >"$OUT"

    LESS_FILE[$X]=`basename $OUT`
    let X=X+1
done

if [ $X -eq 0 ]; then
    exit 0
fi

cd "$DIR"
less "${LESS_FILES[@]}"
