#!/usr/bin/env ruby

require 'json'
require 'yaml'

files = ARGV
files = [ "-" ] if ARGV.length == 0

begin
  files.each do |filename|
    f = $stdin
    f = File.new(filename) unless filename == "-"
    puts YAML.load(f.read).to_json
  end
rescue => e
  puts e
  exit 1
end
