#!/bin/sh

# N.B.: the current version of clang-format used by Envoy needs to be on the PATH.
# Typically, binaries can be found at http://releases.llvm.org/download.html.

[ -n "${CHAIN_HOOKS_DEBUG_HELPERS}" ] && . "${CHAIN_HOOKS_DEBUG_HELPERS}"

_hooks_debug pre-commit format check

ROOT=$(cd `dirname $0` && cd ../.. && pwd)
cd "${ROOT}"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    _hooks_debug "format check:" `git diff --cached --name-only --diff-filter=ACMR -z HEAD`

    if ! git diff --cached --name-only --diff-filter=ACMR -z HEAD | \
            xargs -0 -L 1 ./tools/code_format/check_format.py check; then
        RED="$(tput setaf 1)"
        RESET="$(tput sgr0)"

        echo >&2 "${RED}ERROR: one or more files needs formatting fixes.${RESET}"
        exit 1
    fi
fi

exit 0
